
version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: app_database
    restart: always
    ports:
      - "27017:27017"
    env_file: "backend/db.env"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: vueapp
    volumes:
      - mysql_data:/data/db


  node:
    build:

  nginx:
    build: backend 
    container_name: app_webserver
    restart: always
    ports:
      - 80:80

  frontend:
    container_name: app_frontend
    build: 
      context: frontend
    volumes:
      - frontend:app/frontend
    
volumes:
  mongo_data:
    driver: local