
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: app_database
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: vueapp
    volumes:
      - mongo_data:/data/db


  node:
    build: 
  nginx:
    build: backend 
    container_name: app_webserver
    restart: always
    ports:
      - 80:80

  frontend:
    container_name: app_frontend
    build: 
      context: frontend
    volumes:
      - frontend:app/frontend
    
volumes:
  mongo_data:
    driver: local